// Database of accredited Eye Hospitals & District Ophthalmology Centers
// Calibrated for community health workers and rural patients across Maharashtra and major regions

export const NEARBY_HOSPITALS = [
  {
    id: 'hosp-1',
    name: 'District Civil Hospital — Dept. of Ophthalmology',
    type: 'Government District Hospital',
    district: 'Satara',
    region: 'Maharashtra',
    distance: '2.4 km',
    doctor: 'Dr. Smita Deshmukh, MS (Ophth)',
    doctorTitle: 'District Ophthalmologist & Retina Consultant',
    phone: '+91 2162 234120',
    address: 'Near Sadar Bazar, Civil Hospital Road, Satara, Maharashtra 415001',
    opdTimings: 'Mon – Sat: 8:30 AM – 3:30 PM (Free Walk-in)',
    isGovt: true,
    isPMJAY: true,
    facilities: ['Ayushman Bharat PMJAY Free', 'Slit-Lamp Biomicroscopy', 'Direct/Indirect Ophthalmoscopy', 'Diabetic Eye Clinic'],
    mapQuery: 'District Civil Hospital Satara Ophthalmology Department',
    googleMapsUrl: 'https://www.google.com/maps/search/District+Civil+Hospital+Satara+Eye+Department'
  },
  {
    id: 'hosp-2',
    name: 'Shirwal Rural Hospital & Community Vision Center',
    type: 'Sub-District Community Health Center',
    district: 'Satara',
    region: 'Maharashtra',
    distance: '5.1 km',
    doctor: 'Dr. Rahul Mane, MBBS, DOMS',
    doctorTitle: 'Medical Officer (Eye Specialist)',
    phone: '+91 2169 242045',
    address: 'Pune-Bangalore Highway, Shirwal, Satara District 412801',
    opdTimings: 'Mon – Fri: 9:00 AM – 4:00 PM',
    isGovt: true,
    isPMJAY: true,
    facilities: ['Ayushman Bharat Free', 'Fundus Screening Hub', 'Weekly Retina Specialist Camp'],
    mapQuery: 'Rural Hospital Shirwal Satara',
    googleMapsUrl: 'https://www.google.com/maps/search/Rural+Hospital+Shirwal+Satara'
  },
  {
    id: 'hosp-3',
    name: 'Sanjeevan Retinal Laser & Eye Hospital',
    type: 'Tertiary Vitreo-Retinal Center',
    district: 'Satara',
    region: 'Maharashtra',
    distance: '6.8 km',
    doctor: 'Dr. Amitav Kulkarni, MS, FVR',
    doctorTitle: 'Senior Vitreo-Retinal Surgeon',
    phone: '+91 2162 281599',
    address: 'Plot 14, Radhika Road, Opp. ST Stand, Satara 415002',
    opdTimings: 'Mon – Sat: 9:30 AM – 7:00 PM',
    isGovt: false,
    isPMJAY: true,
    facilities: ['Optical Coherence Tomography (OCT)', 'Green Laser Photocoagulation', 'Anti-VEGF Therapy', 'Emergency Vitrectomy'],
    mapQuery: 'Sanjeevan Eye Hospital Satara',
    googleMapsUrl: 'https://www.google.com/maps/search/Sanjeevan+Retina+Eye+Hospital+Satara'
  },
  {
    id: 'hosp-4',
    name: 'Sassoon General Hospital & BJ Government Medical College',
    type: 'Government Medical College & Tertiary Hospital',
    district: 'Pune',
    region: 'Maharashtra',
    distance: '54 km',
    doctor: 'Prof. (Dr.) Vandana Phadke, MS',
    doctorTitle: 'Head of Ophthalmology & Vitreo-Retina Unit',
    phone: '+91 20 2612 8000',
    address: 'Station Road, Near Pune Railway Station, Pune 411001',
    opdTimings: 'Daily 24x7 Emergency • OPD Mon – Sat 8:00 AM – 2:00 PM',
    isGovt: true,
    isPMJAY: true,
    facilities: ['Ayushman Bharat PMJAY Free', 'Advanced Heidelberg OCT', 'Anti-VEGF Center', 'Pan-Retinal Laser', 'Sub-Speciality DR Clinic'],
    mapQuery: 'Sassoon Hospital Pune Ophthalmology Department',
    googleMapsUrl: 'https://www.google.com/maps/search/Sassoon+General+Hospital+Pune+Eye+Department'
  },
  {
    id: 'hosp-5',
    name: 'National Institute of Ophthalmology (NIO)',
    type: 'Super-Specialty Retina Research Institute',
    district: 'Pune',
    region: 'Maharashtra',
    distance: '58 km',
    doctor: 'Dr. Aditya Kelkar, MS, FRCS',
    doctorTitle: 'Vitreo-Retina & Cataract Specialist',
    phone: '+91 20 6606 0000',
    address: 'Ghole Road, Near Balgandharva, Shivajinagar, Pune 411005',
    opdTimings: 'Mon – Sat: 8:30 AM – 8:00 PM',
    isGovt: false,
    isPMJAY: true,
    facilities: ['State-of-the-Art SD-OCT', 'Fundus Fluorescein Angiography (FFA)', 'Micro-Incision Vitrectomy (MIVS)', 'Low Vision Rehabilitation'],
    mapQuery: 'National Institute of Ophthalmology Pune',
    googleMapsUrl: 'https://www.google.com/maps/search/National+Institute+of+Ophthalmology+Pune'
  },
  {
    id: 'hosp-6',
    name: 'KEM Hospital & Research Centre — Dept. of Eye',
    type: 'Trust Hospital & Research Center',
    district: 'Pune',
    region: 'Maharashtra',
    distance: '56 km',
    doctor: 'Dr. Meena Agarwal, MD (AIIMS)',
    doctorTitle: 'Consultant Vitreo-Retinal Surgeon',
    phone: '+91 20 6603 7300',
    address: '489 Rasta Peth, Sardar Moodliar Road, Pune 411011',
    opdTimings: 'Mon – Sat: 9:00 AM – 5:00 PM',
    isGovt: false,
    isPMJAY: true,
    facilities: ['Diabetic Macular Edema Clinic', 'OCT Angiography', 'Subsidized Laser Treatment', 'PMJAY Beneficiary Helpdesk'],
    mapQuery: 'KEM Hospital Pune Eye Department',
    googleMapsUrl: 'https://www.google.com/maps/search/KEM+Hospital+Pune+Eye+Department'
  },
  {
    id: 'hosp-7',
    name: 'Sir J.J. Group of Hospitals — Dept. of Ophthalmology',
    type: 'Government Apex Medical Center',
    district: 'Mumbai',
    region: 'Maharashtra',
    distance: '210 km',
    doctor: 'Prof. (Dr.) T. P. Lahane, MS, Padmashree',
    doctorTitle: 'Director Medical Education & Retina Consultant',
    phone: '+91 22 2373 5555',
    address: 'J.J. Hospital Compound, Byculla, Mumbai 400008',
    opdTimings: 'Mon – Sat: 8:00 AM – 1:30 PM (Free)',
    isGovt: true,
    isPMJAY: true,
    facilities: ['State Apex Retina Referral Center', 'Free Surgical Vitrectomy', 'Complete PMJAY / MJPJAY Coverage', 'Emergency Eye Trauma'],
    mapQuery: 'JJ Hospital Mumbai Eye Department',
    googleMapsUrl: 'https://www.google.com/maps/search/JJ+Hospital+Mumbai+Eye+Department'
  },
  {
    id: 'hosp-8',
    name: 'Dr. Rajendra Prasad Centre for Ophthalmic Sciences (AIIMS)',
    type: 'National Apex Institute of Ophthalmology',
    district: 'National / All-India',
    region: 'New Delhi',
    distance: 'Apex Center',
    doctor: 'Prof. (Dr.) Atul Kumar, MD, FAMS',
    doctorTitle: 'Chief, Vitreo-Retina Services',
    phone: '+91 11 2658 8500',
    address: 'AIIMS Campus, Ansari Nagar, New Delhi 110029',
    opdTimings: 'Mon – Sat: 8:00 AM – 1:00 PM',
    isGovt: true,
    isPMJAY: true,
    facilities: ['National Apex Referral Institute', 'Free / Central CGHS & PMJAY', 'Comprehensive Macular & PDR Surgical Units'],
    mapQuery: 'AIIMS RP Centre Eye Hospital New Delhi',
    googleMapsUrl: 'https://www.google.com/maps/search/AIIMS+RP+Centre+Eye+Hospital+New+Delhi'
  }
];

export const getLiveMapsSearchUrl = (userCoords = null) => {
  if (userCoords && userCoords.latitude && userCoords.longitude) {
    return `https://www.google.com/maps/search/eye+specialist+ophthalmologist+retina+hospital/@${userCoords.latitude},${userCoords.longitude},13z`;
  }
  return 'https://www.google.com/maps/search/eye+specialist+ophthalmologist+retina+hospital+near+me';
};
